---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "8ea1fc80-e180-4503-b9a8-90715c230540"
    jetic.io/integration.name: "Jetlet-Bean-Error"
    jetic.io/integration.revision: "50"
    jetic.io/integration.uuid: "7e367755-71ec-4359-84ce-8aaaf2b64bf4"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "cb34a175-7664-438e-9d8f-481373aa66ff"
  name: "jetlet-bean-error"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies: []
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |-
      //
      // To run this integration use:
      //
      // kamel run Jetlet_Bean_Error.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=Jetlet-Bean-Error

      import org.apache.camel.LoggingLevel

      from('timer:timer?daemon=true&delay=1000&fixedRate=false&period=10000&repeatCount=0').routeId('route-1')
          .setBody().groovy('new Random().nextInt(5) + 1').id('setBody: 00')
          .log(LoggingLevel.INFO, 'log', 'Generated Number: ${body}').id('log: 00')
          .choice().id('messageRouter: 00')
              .when().simple('${body} <= 2')
                  .to('direct:beanProcess').id('direct: beanProcess')
              .endChoice()
              .when().simple('${body} > 2')
                  .to('direct:jetletProcess').id('direct: jetletProcess')
              .endChoice()
          .end()
          .log(LoggingLevel.INFO, 'log', 'Result: ${body} - Property ErrorProcessed: ${exchangeProperty.ErrorProcessed}').id('log: 01')

      from('direct:beanProcess').routeId('route-2')
          .to('bean:beanHandler').id('bean: 00')

      from('direct:jetletProcess').routeId('route-3')
          .to('kamelet:errorhandler-sink')
    name: "Jetlet-Bean-Error.groovy"
  - content: |-
      import org.apache.camel.BindToRegistry;
      import org.apache.camel.Exchange;
      import org.apache.camel.Processor;

      public class BeanHandler implements Processor {

          @Override
          public void process(Exchange exchange) throws Exception {
              Integer body = exchange.getIn().getBody(Integer.class);
              String message;
              if (body != null && body == 1) {
                  message = "Got Code " + body;
              } else {
                  message = "Got Unknown Code " + body;
              }
              exchange.setProperty("ErrorProcessed", false);
              exchange.getMessage().setBody(message);
          }

          @BindToRegistry
          public Processor beanHandler() {
              return this;
          }
      }
    name: "BeanHandler.java"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.revision"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
